home:
  path: /
  defaults: { _controller: AppBundle:Default:index, active:false }

rules:
  path: /rules
  defaults: { _controller: AppBundle:Rules:index }

general:
  path: /rules/general/{active}
  defaults: { _controller: AppBundle:Rules:general, active:false }

power:
  path: /rules/power/{active}
  defaults: { _controller: AppBundle:Rules:power, active:false }

terrain:
  path: /rules/terrain/{active}
  defaults: { _controller: AppBundle:Rules:terrain, active:false }

turn:
  path: /rules/turn/{active}
  defaults: { _controller: AppBundle:Rules:turn, active:false }

unit:
  path: /rules/unit/{active}
  defaults: { _controller: AppBundle:Rules:unit, active:false }

house_rules:
  path: /rules/houserules/{active}
  defaults: { _controller: AppBundle:Rules:houseRules, active:false }

battle_calculator:
  path: /battlecalculator/{active}
  defaults: { _controller: AppBundle:BattleCalculator:index, active:false }

downloads:
  path: /downloads/{active}
  defaults: { _controller: AppBundle:Default:downloads, active:false }

links:
    path: /links/{active}
    defaults: { _controller: AppBundle:Default:links, active:false }